s1 = open("lab7_3_procs_1","r")
s2 = open("lab7_3_procs_2","r")
s4 = open("lab7_3_procs_4","r")
s8 = open("lab7_3_procs_8","r")
x1 = x2 = x4 = x8 = []
tic()
readdlm(s1)
#read!(s1,x1)
println("time1 =", toq())
tic()
readdlm(s2)
#read!(s2,x2)
println("time2 =", toq())
tic()
readdlm(s4)
#read!(s4,x4)
println("time4 =", toq())
tic()
readdlm(s8)
#read!(s8,x8)
println("time8 =", toq())
